spring.application.name=Many_to_One

spring.datasource.url=jdbc:mysql://localhost:3306/one_to_many_demo
spring.datasource.username=root
spring.datasource.password=Abhishek@1137

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=Abhi
spring.security.user.password=1137

server.port=8080

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs

# Logging
logging.level.root=INFO
logging.level.com.abhishek.demo=DEBUG
logging.level.org.springframework.security=DEBUG